<a href="https://colab.research.google.com/github/Nikita1013/Machine-Learning-with-Python/blob/master/5_1_7_Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Matrix using Numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])

In [3]:
print(matrix_1)

[[2 3]
 [6 7]]


Shape of a Matrix

In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
print(matrix_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [9]:
random_matrix = np.random.rand(3,3)

We get all the values betweeen 0 to 1 in float

In [10]:
print(random_matrix)

[[0.96891439 0.75515326 0.82322064]
 [0.23784286 0.20052646 0.1307448 ]
 [0.39568236 0.47477905 0.1108931 ]]


Creating Matrix with Random integers

In [11]:
# Creating matrix with random integers
random_interger_matrix = np.random.randint(100, size=(4,5))
# 100 -> it will consider from number 0 to 100
print(random_interger_matrix)

[[58 21 83 52 10]
 [48 56 77 31 28]
 [34 20 15 25 80]
 [82 73  3 36 74]]


Matrix with all the values as 1

In [16]:
# Prints all the 1's in Matrix
matrix_3 = np.ones((2,3))
print(matrix_3)
# It gives float type

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# Use dtype=int for getting interger type numbers in the matrix
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


NULL  Matrix or Zero Matrix ==> All the values are 0's

In [18]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity Matrix

- All the diagonal values ar 1 and other values as 0

In [19]:
# creating Identity Matrix
identity_matrix =np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Transpose of a Matrix**

In [20]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[92 88 40 37 50]
 [52 30 45 12 55]
 [74 64 69 38 43]
 [54 41  7 60 35]]


In [21]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[92 52 74 54]
 [88 30 64 41]
 [40 45 69  7]
 [37 12 38 60]
 [50 55 43 35]]


In [22]:
transpose_of_a.shape

(5, 4)