<a href="https://colab.research.google.com/github/Nikita1013/Machine-Learning-with-Python/blob/master/5_1_9_Matrix_Operations_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy Library

In [1]:
import numpy as np

**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [5]:
# creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [6]:
print(A)

[[2 3]
 [4 5]]


In [7]:
print(B)

[[6 7]
 [8 9]]


In [8]:
A.shape

(2, 2)

In [9]:
B.shape

(2, 2)

Adding two Matrices

In [10]:
sum = A + B

In [11]:
print(sum)

[[ 8 10]
 [12 14]]


In [12]:
sum.shape

(2, 2)

In [13]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))

matrix_2 = np.random.randint(10,size=(3,3))

In [14]:
print(matrix_1)

[[8 5 0]
 [3 8 4]
 [0 1 6]]


In [15]:
print(matrix_2)

[[1 5 1]
 [4 1 7]
 [6 9 4]]


In [16]:
sum = matrix_1 + matrix_2

In [17]:
print(sum)

[[ 9 10  1]
 [ 7  9 11]
 [ 6 10 10]]


In [18]:
matrix_3 = np.random.randint(10, size=(3,3))

matrix_4 = np.random.randint(10, size=(3,4))

In [19]:
print(matrix_3)

[[5 3 6]
 [3 1 3]
 [0 0 4]]


In [20]:
print(matrix_4)

[[8 1 3 7]
 [2 1 7 1]
 [4 6 7 4]]


In [23]:
sum = matrix_3 + matrix_4
# we get this error if the matrices are not in equal size

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

Two Matrices can be added only if they have the same shape

Matrix Subtraction

In [24]:
# creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [25]:
print(A)

[[2 3]
 [4 5]]


In [26]:
print(B)

[[6 7]
 [8 9]]


In [27]:
subtract = A - B
print(subtract)

[[-4 -4]
 [-4 -4]]


In [28]:
# creating two random  matrices with random values
matrix_5 = np.random.randint(10, size=(3,3))
matrix_6 = np.random.randint(20, size=(3,3))

In [29]:
print(matrix_5)

[[7 1 0]
 [5 0 5]
 [5 9 4]]


In [31]:
print(matrix_6)

[[ 6  9  5]
 [13 14  7]
 [ 7  2  5]]


In [32]:
diff = np.subtract(matrix_5, matrix_6)

In [33]:
print(diff)

[[  1  -8  -5]
 [ -8 -14  -2]
 [ -2   7  -1]]


Multiplying a matrix by a Scalar

In [34]:
x =5
y = np.random.randint(10, size=(4,4))

print(y)

[[7 3 2 9]
 [8 0 6 9]
 [8 7 6 8]
 [2 4 2 1]]


In [35]:
product = np.multiply(x,y)

print(product)

[[35 15 10 45]
 [40  0 30 45]
 [40 35 30 40]
 [10 20 10  5]]


Multiplying 2 matrices

In [37]:
# create two matrices with random values
matrix_7 = np.random.randint(5, size=(3,3))
matrix_8 = np.random.randint(5, size=(3,4))

In [38]:
print(matrix_7)

[[1 4 0]
 [3 0 4]
 [4 0 3]]


In [39]:
print(matrix_8)

[[2 2 3 0]
 [0 1 4 1]
 [0 1 2 3]]


In [40]:
product = np.dot(matrix_7, matrix_8)

In [41]:
print(product)

[[ 2  6 19  4]
 [ 6 10 17 12]
 [ 8 11 18  9]]


In [42]:
product.shape

(3, 4)

In [44]:
# create two matrices with random values
matrix_9 = np.random.randint(5, size=(3,3))
matrix_10 = np.random.randint(5, size=(4,4))

In [46]:
product = np.dot(matrix_9, matrix_10)
# we get error here as the column in matrix_9 and matrix_10 doesn't match

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

Element wise Matrix Maultiplication

In [51]:
# create two matrices with random values
matrix_11 = np.random.randint(5, size=(3,3))
matrix_12 = np.random.randint(5, size=(3,3))

In [52]:
print(matrix_11)

[[2 0 0]
 [3 3 3]
 [4 3 3]]


In [53]:
print(matrix_12)

[[0 1 4]
 [1 3 4]
 [1 2 0]]


In [54]:
product = np.multiply(matrix_11, matrix_12)

In [55]:
print(product)

[[ 0  0  0]
 [ 3  9 12]
 [ 4  6  0]]
