<a href="https://colab.research.google.com/github/Nikita1013/Machine-Learning-with-Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [3]:
# Importing the numpy lib
import numpy as np

# Creating array using numpy
# Creating 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [5]:
print(arr2)

[1 2 3 4 5]


In [6]:
# Making 2D array with nested list
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [7]:
np.arange(0,10,2).reshape(5,1)   #(start, end, step)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
# Printing the array with all 1's
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# Identity Matrix
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [10]:
# Attributes of Numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n",arr)
print("Shape: ", arr.shape)
print("Number of Dimensions: ",arr.ndim)
print("SIze (number of elements) : ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size (in bytes) : ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimensions:  2
SIze (number of elements) :  6
Data Type:  int64
Item Size (in bytes) :  8


In [11]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise addition
print("Addition : ",arr1+arr2)


# Element wise substraction
print("Substraction : ", arr2-arr1)

# Element wise multiplication
print("Multiplication : ", arr1*arr2)

# Element wise division
print("Division : ", arr2/arr1)

Addition :  [11 22 33 44 55]
Substraction :  [ 9 18 27 36 45]
Multiplication :  [ 10  40  90 160 250]
Division :  [10. 10. 10. 10. 10.]


In [13]:
# Universal Function
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [14]:
# Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(arr[0][0])
print(arr[1][1])
print(arr[2][2])
print(arr[2][3])

1
6
11
12


In [20]:
arr[1:,2:]
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [21]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [22]:
# Modify Array Elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [25]:
# statistical concept -- Normalization
# Converting the data such that the mean is 0 and standard deviation is 1
data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean)/ std_dev
print("Normalized data : ",normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [26]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean : ", mean)

# Median
median = np.median(data)
print("Median : ", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation : ", std_dev)

# Variance
variance = np.var(data)
print("Variance : ", variance)

Mean :  5.5
Median :  5.5
Standard Deviation :  2.8722813232690143
Variance :  8.25


In [36]:
# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])