<a href="https://colab.research.google.com/github/Nikita1013/Machine-Learning-with-Python/blob/master/Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python


Advantages of NumPy Arrays:
   
   1. Allows several Mathematical Operations
   2. Faster Operations

In [2]:
import numpy as np

List vs NumPy -  Time Taken

In [3]:
from time import process_time

Time taken by a list

In [8]:
list1 = [i for i in range(10000)]

start_time = process_time()

list1 = [i+5 for i in list1]

end_time = process_time()

print(end_time - start_time)

0.00044211500000024273


In [10]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00013466799999939383


Numpy Arrays

In [11]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [12]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [13]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
a.shape

(4,)

In [16]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
b.shape

(2, 4)

In [19]:
c = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype=float)
print(c)
c.shape

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


(3, 3)

Initial Placeholders in numpy arrays

In [20]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# array of a particular value
z = np.full((5,4),10)    # 5 rows and 4 columns
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [33]:
# create a identity matrix (number of rows and columns must be same)
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [35]:
# create a numpy array with random values
# Random values is between 0 and 1
b = np.random.random((3,4))

print(b)

[[0.11534597 0.10696157 0.91685337 0.9981583 ]
 [0.76431696 0.31906217 0.67084487 0.79256649]
 [0.0201696  0.386612   0.3496464  0.08252594]]


In [40]:
# random values array within a specific range
c = np.random.randint(10,100,(3,4))
print(c)

[[69 19 60 84]
 [18 17 18 57]
 [10 71 17 20]]


In [43]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [45]:
# array of evenly spaced values ---> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [48]:
# Convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a Numpy array

In [51]:
c = np.random.randint(10,90,(5,5))
print(c)


[[68 20 24 57 33]
 [76 21 47 15 39]
 [46 49 48 82 62]
 [85 89 69 27 27]
 [22 17 16 37 82]]


In [52]:
print(c.shape)

(5, 5)


In [53]:
# number of dimensions
print(c.ndim)  #gives the dimension it gives 2 as it is two dimensional array

2


In [54]:
# checking the data type of the values in an array
print(c.dtype)

int64


Mathermatical Operations on a np array


In [55]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or join two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [65]:
a = np.random.randint(10,20,(3,3))
b = np.random.randint(0,10,(3,3))

print(a)
print(b)

[[15 17 12]
 [12 13 18]
 [10 13 10]]
[[8 3 1]
 [1 4 2]
 [4 5 0]]


In [66]:
print(a+b)

[[23 20 13]
 [13 17 20]
 [14 18 10]]


In [70]:
print(a-b)

[[ 7 14 11]
 [11  9 16]
 [ 6  8 10]]


In [68]:
print(a*b)

[[120  51  12]
 [ 12  52  36]
 [ 40  65   0]]


In [71]:
print(a/b)

[[ 1.875       5.66666667 12.        ]
 [12.          3.25        9.        ]
 [ 2.5         2.6                inf]]


/tmp/ipython-input-71-4070583000.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a/b)


In [74]:
print(np.add(a,b))

print(np.subtract(a,b))

print(np.multiply(a,b))

print(np.divide(a,b))

[[23 20 13]
 [13 17 20]
 [14 18 10]]
[[ 7 14 11]
 [11  9 16]
 [ 6  8 10]]
[[120  51  12]
 [ 12  52  36]
 [ 40  65   0]]
[[ 1.875       5.66666667 12.        ]
 [12.          3.25        9.        ]
 [ 2.5         2.6                inf]]


/tmp/ipython-input-74-3252657645.py:7: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(a,b))


Array Manipulation

In [75]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 9 3]
 [1 5 7]]
(2, 3)


In [76]:
# transpose  ---> if array is (2,3) the transpose makes it (3,2)
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 1]
 [9 5]
 [3 7]]
(3, 2)


In [77]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 1]
 [9 5]
 [3 7]]
(3, 2)


In [79]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 1 1]
 [0 7 7]]
(2, 3)


In [82]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 1]
 [1 0]
 [7 7]]
(3, 2)
